# For Vite + React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Build settings (if not configured in Netlify UI)
[build]
  command = "npm run build"
  publish = "dist"